version: "3.8"

services:
  sucursal-db:
    image: mysql
    networks:
      - spring-web
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=level1
      - MYSQL_DATABASE=level1
      - MYSQL_USER=level1
      - MYSQL_PASSWORD=level1
  
  dados-db:
    image: mysql
    networks:
      - spring-web
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=dados
      - MYSQL_DATABASE=dados
      - MYSQL_USER=dados
      - MYSQL_PASSWORD=dados
  
  mongo-dados:
    image: mongo:latest
    ports:
      - "27017:27017"
    networks:
      - spring-web
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongo
      - MONGO_INITDB_ROOT_PASSWORD=mongo
      - MONGO_INITDB_DATABASE=mongo
networks:
  spring-web:
